name: Go

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        PGDATABASE: postgres
        PGHOST: postgres
        PGPORT: 5432
        PGPASSWORD: postgres
